# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_paciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='name',
            new_name='nome',
        ),
    ]
