# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0006_auto_20171021_1131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InserirExame',
            new_name='Exames',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='file',
            field=models.FileField(blank=True, upload_to='', verbose_name='clinica.Exames.file'),
        ),
    ]
