# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0007_auto_20171021_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exames',
            options={'verbose_name': 'nome'},
        ),
    ]
