# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0008_auto_20171021_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exames',
            options={'verbose_name': 'Exame', 'verbose_name_plural': 'Exames'},
        ),
        migrations.AddField(
            model_name='exames',
            name='CPF',
            field=models.CharField(blank=True, max_length=11, verbose_name='clinica.Paciente.cpf'),
        ),
    ]
