# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0009_auto_20171021_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exames',
            options={},
        ),
        migrations.RemoveField(
            model_name='exames',
            name='CPF',
        ),
        migrations.RemoveField(
            model_name='exames',
            name='file',
        ),
        migrations.RemoveField(
            model_name='exames',
            name='nome',
        ),
        migrations.AddField(
            model_name='exames',
            name='descrip',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='exames',
            name='icon',
            field=models.FileField(blank=True, upload_to='media/exames/icons'),
        ),
        migrations.AddField(
            model_name='exames',
            name='title',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='file',
            field=models.FileField(blank=True, upload_to='media/pacientes/exames'),
        ),
    ]
