# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0010_auto_20171021_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='exames',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='exames',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
