# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0013_auto_20171021_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exames',
            name='icon',
            field=models.FileField(blank=True, upload_to='exames/icons'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='file',
            field=models.FileField(blank=True, upload_to='pacientes/exames'),
        ),
    ]
