# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0014_auto_20171021_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='codigo',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name=b'Codigo'),
        ),
    ]
