# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0015_paciente_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='codigo',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='Codigo'),
        ),
    ]
