# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0016_auto_20171031_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(max_length=200, verbose_name=b'Nome Completo'),
        ),
    ]
