# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0017_auto_20171106_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColetaAgendada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=50, verbose_name=b'Rua')),
                ('numero', models.CharField(max_length=20, verbose_name=b'Numero')),
                ('bairro', models.CharField(max_length=50, verbose_name=b'Bairro')),
                ('complemento', models.CharField(max_length=100, verbose_name=b'Complemento')),
                ('telefone', models.IntegerField(verbose_name=b'Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name=b'Email')),
                ('nome', models.CharField(max_length=50, verbose_name=b'Nome Completo')),
            ],
        ),
    ]
